name: Deploy
on:
  push:
    branches:
      - production

jobs:
  build:
    name: Build process
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn ci
      - name: Lint project
        run: yarn lint:prod
      # - name: Run tests
      #   run: yarn test
      # - name: Build server files
      #   run: yarn build
      - name: Generate static files
        run: yarn generate
      - name: Create artifact
        run: |
          PACKAGE_VERSION=`node -e "console.log(require('./package.json').version);"`
          PACKAGE_NAME="byloth-website-v${PACKAGE_VERSION}.tgz"
          yarn pack
          tar -xzvf "${PACKAGE_NAME}" -C "."
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: byloth-website
          path: package/dist

  #
  # test:
  #   name: Test process
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - [...]
  #

  deploy:
    name: Deploy process
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: byloth-website
          path: dist

      - name: Mirror remote FTP directory
        shell: bash
        run: |
          lftp -c " \
            set ssl:check-hostname no; \
            open ${FTP_HOST}; \
            user ${FTP_USER} ${FTP_PASS}; \
            mirror --delete \
                   --reverse \
                   --verbose \
              \
              dist/ ./; \
              bye \
          "

        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
